# Generated by Django 5.2.12 on 2026-03-24 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_modelo_alter_cor_options_alter_cor_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=0, null=True)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True)),
                ('acessorios', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='core.acessorio')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='core.cor')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='core.modelo')),
            ],
        ),
    ]
