# Generated by Django 5.2.12 on 2026-03-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_veiculo_acessorios_veiculo_acessorios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
